//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOutV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutina
    {
        public rutina()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id { get; set; }
        public string maquinas { get; set; }
        public string descanso { get; set; }
        public string series { get; set; }
        public string repeticiones { get; set; }
        public Nullable<System.DateTime> fecha_uso { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
