//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOutV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.rutina = new HashSet<rutina>();
        }
    
        public int id { get; set; }
        public string usuario1 { get; set; }
        public string pass { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public int edad { get; set; }
        public string correo { get; set; }
        public double altura { get; set; }
        public double peso { get; set; }
        public double ind_muscular { get; set; }
        public double ind_grasa { get; set; }
    
        public virtual ICollection<rutina> rutina { get; set; }
    }
}
